"""Build Table 2 — Cohort overview.

One row per cohort with: role (training vs zero-shot external), site, n,
prevalence, label SOP, and a short note on intended role in the study.

Outputs:
    paper_figures/tables/T2_cohort_overview.csv
    paper_figures/tables/T2_cohort_overview.md
    paper_figures/docs/T2_cohort_overview.md
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(os.environ.get("AAS_PROJECT_ROOT", Path(__file__).resolve().parents[3]))
sys.path.insert(0, str(ROOT / "AAS_Code" / "analysis" / "figures"))
from _data import COHORT_META, COHORT_ORDER, load_predictions  # noqa: E402

OUT = ROOT / "tables"
DOCS = ROOT / "docs"
OUT.mkdir(parents=True, exist_ok=True)
DOCS.mkdir(parents=True, exist_ok=True)


COHORT_DISPLAY = {
    "datasetA":      "D",
    "datasetB_v6":   "V1",
    "xiangya_720":   "V2",
    "xiangya_16218": "V3",
}

COHORT_FULL = {
    "datasetA":      "Development cohort",
    "datasetB_v6":   "External validation 1",
    "xiangya_720":   "External validation 2",
    "xiangya_16218": "External validation 3",
}

COHORT_NOTE = {
    "datasetA":      "Model development — all LightGBM stage risk models, "
                     "the CP3 logistic-regression text model, policy thresholds, "
                     "safety-layer hyperparameters, and the specialist and "
                     "coordinator LLM prompts were trained or iterated on this "
                     "cohort and then frozen before any external-cohort exposure.",
    "datasetB_v6":   "Strict zero-shot external validation, same province as the "
                     "training cohort.",
    "xiangya_720":   "Strict zero-shot external validation, geographically and "
                     "institutionally independent of the training site; "
                     "triple-physician-adjudicated gold standard.",
    "xiangya_16218": "Strict zero-shot external validation at scale; gold labels "
                     "generated by LLM-assisted candidate extraction with dual "
                     "independent physician adjudication and third-physician "
                     "arbitration.",
}


def main() -> None:
    rows: list[dict] = []
    for cohort in COHORT_ORDER:
        meta = COHORT_META[cohort]
        # Compute exact counts from the data
        pred = load_predictions(cohort, "multi_agent")
        n = len(pred)
        pos = int((pred.y == 1).sum())
        neg = int((pred.y == 0).sum())
        prev = pos / n
        rows.append({
            "cohort_internal": cohort,
            "cohort_id":      COHORT_DISPLAY[cohort],
            "full_name":      COHORT_FULL[cohort],
            "role":           meta["role"],
            "site":           meta["site"],
            "site_label":     meta["site_label"],
            "n":              n,
            "n_AAS_pos":      pos,
            "n_AAS_neg":      neg,
            "prevalence":     prev,
            "label_sop":      meta["label_sop"],
            "study_role_note": COHORT_NOTE[cohort],
        })

    df = pd.DataFrame(rows)
    df.to_csv(OUT / "T2_cohort_overview.csv", index=False)

    # ---- Markdown table ----
    md: list[str] = []
    md.append("# Table 2 — Cohort overview\n\n")
    md.append("One development cohort plus three independent zero-shot external "
              "validation cohorts (total n = 16,561 patients, prevalence "
              "28.0 – 52.3%). The three external cohorts were not consulted "
              "during model training, prompt iteration, threshold calibration, "
              "or hyperparameter selection.\n\n")
    md.append("| ID | Cohort name | Role | Site | n | AAS+ | AAS− | Prevalence | Label generation | Notes |\n")
    md.append("|---|---|---|---|---:|---:|---:|---:|---|---|\n")
    for _, r in df.iterrows():
        md.append(
            f"| **{r['cohort_id']}** | {r['full_name']} | {r['role']} | {r['site']} | "
            f"{int(r['n']):,} | {int(r['n_AAS_pos']):,} | "
            f"{int(r['n_AAS_neg']):,} | {r['prevalence']*100:.1f}% | "
            f"{r['label_sop']} | {r['study_role_note']} |\n"
        )
    md.append("\n")
    md.append("*AAS, acute aortic syndrome (includes aortic dissection, "
              "intramural haematoma, penetrating atherosclerotic ulcer).*\n")

    (OUT / "T2_cohort_overview.md").write_text("".join(md))

    # ---- Doc ----
    doc = [
        "# T2 — Cohort overview | explanation document\n\n",
        "## Purpose\n",
        "Establishes the four-cohort study design with a clear development vs. "
        "zero-shot boundary. This is the first table the reader meets and "
        "must communicate three things at a glance: (i) Cohort D alone was "
        "used for all model fitting and prompt iteration; (ii) the three "
        "external cohorts span two additional tertiary centres and a wide "
        "prevalence range; (iii) the largest external cohort uses an LLM-"
        "assisted physician-adjudicated SOP that produces gold labels (not "
        "silver / not noisy).\n\n",
        "## Recommended placement\n",
        "Manuscript Methods §2 or Results §1 — must precede Table 1.\n\n",
        "## Reading the table\n",
        "- *Role* column makes the training vs. zero-shot boundary explicit.\n",
        "- *Site* column shows the three-centre design.\n",
        "- *Label generation* column distinguishes the three label SOPs.\n",
        "- *Notes* column states what each cohort tests in plain English.\n\n",
        "## Sources\n",
        "- Counts derived directly from per-patient prediction frames via "
        "`paper_figures._data.load_predictions(cohort, 'multi_agent')`.\n",
        "- Site, role and SOP metadata in `paper_figures._data.COHORT_META`.\n",
        "Generated by `paper_figures/tables/build_t2_cohort_overview.py`.\n",
    ]
    (DOCS / "T2_cohort_overview.md").write_text("".join(doc))
    print(f"Wrote {OUT/'T2_cohort_overview.csv'}")
    print(f"Wrote {OUT/'T2_cohort_overview.md'}")
    print(f"Wrote {DOCS/'T2_cohort_overview.md'}")


if __name__ == "__main__":
    main()
